name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          if [ ! -d node_modules ]; then
            yarn install --frozen-lockfile
          else
            echo "node_modules already cached, skipping install"
          fi
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run ESLint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: setup-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          if [ ! -d node_modules ]; then
            yarn install --frozen-lockfile
          else
            echo "node_modules already cached, skipping install"
          fi

      - name: Run Tests with Coverage
        run: yarn test:cov

      - name: Upload Coverage Report (Optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/